flora:
  N: 600
  plant_growth: 0.1
  lightnings_per_updates: 4 # LPU
  lightnings_success_probability: 0.25 # LSP
  sleep_time: 0.1

wildLife:
  preyInitialPop: 100.0
  predatorInitialPop: 30.0
  alpha_max: 5.0
  beta: 0.1
  gamma: 4
  delta: 0.05
  epsilon: 4.0
  dt: 0.025